### ISSUE TITLE
Import project ideas from wiki page

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/GSoC#1]
Ideas available at the wiki page: https://wiki.sugarlabs.org/go/Development_Team/Project_Ideas must to be reviewed and added to `Ideas-2019.md`

**Comment by pro-panda** [comment]
@quozl @walterbender 
There are a lot of ideas around Sugar in the link and comments, but I don't want to add them unless we have mentors for each idea. Please feel free to take them up.

**Comment by iqraceme** [comment]
Yes, I am interested in mentoring for "port all Sugarizer activities to Sugar, updating sugar-web as needed". I was discussing this idea a few days ago with Samson.

**Comment by iqraceme** [comment]
@pro-panda Is there any format that needs to be followed while adding the idea to Ideas-2019.md  ?

**Comment by quozl** [comment]
Markdown format.  Like it is now?

**Comment by iqraceme** [comment]
Yes, the markdown format that is at the moment in Ideas-2019.md

**Comment by quozl** [comment]
Good.

**Comment by pro-panda** [comment]
@quozl, I'm thinking to take up
> port Sugar shell (module jarabe) to act as an application

but I'm failing to write a description and a list of `suggested issues to work on`. Any suggestions

**Comment by quozl** [comment]
Thanks.  How about this;

On Linux, Sugar is an instance of a class _desktop session manager_, implemented as a full-screen GTK+ application with a subprocess running the Metacity _window manager_, and a datastore accessed through D-Bus.  Sugar does not work properly if run as an _application_ inside another desktop session manager, because the assumptions inherent in being a session manager conflict with the already running session manager.

Then you can try doing that, and start listing what needs to change.

I'm not surprised you haven't found issues.  We don't raise issues unless there is someone interested in tracking or communicating progress.  It is a waste of time otherwise.

You might also look at our roughly 5000 tickets at bugs.sugarlabs.org for anything interesting.  There are new tickets created there regularly.  e-mail notification is broken though, and I've asked for help on systems@ but no answers yet.

**Comment by pro-panda** [comment]
Thanks,
I realised I can't add this yet.

Do we have a developer now who would be willing and able to do it if a student was not available, and who can promise to do it if a student is not selected ?

Also, I'm not sure of how to implement this, so I won't be the best person to mentor. I can co-mentor if someone is willing to take this up

**Comment by quozl** [comment]
Agreed.  Ideas are not the problem.  People are the problem.  :grin:

**Comment by quozl** [comment]
I've briefly looked at the Wiki page again; it is mostly out of date.  Staying alive as an open source project that is distributed to users is the first priority.
