### ISSUE TITLE
Traffic Sign Teaching Activity

### ISSUE THREAD

**Issue by Mohitphulera** [sugarlabs/GSoC#66]
Traffic signs or road signs are signs erected at the side of or above roads to give instructions or provide information to road users. The earliest signs were simple wooden or stone milestones. 

The activity’s main motive is to help a student to learn Traffic Signs or Road Signs. The main idea is to develop an activity which will aware every student of each & every road safety rules.Road safety education is vital for people of all ages. As a responsible citizen, one should be aware of each and every road safety rules. Observation is the key skill you need in ensuring road safety. Safety education begins right from our school. By obeying safety rules and regulations, one can save himself and others on the road. The score will be given as per the correctness of the Traffic Sign Identified. This will help students to learn correct meaning of Road Signs as well as ensure there safety while roaming around in the city.
There can be levels for this activity can be based on types of road signs like Guidance,Warning,Regulation etc.

Suggestions are Welcome

**Comment by quozl** [comment]
Thanks for the idea.  We may use it for next year.  Proposals for this year have closed.

**Comment by kohli6010** [comment]
is this going to be the feature for next year GSoC or can anybody work on this idea

**Comment by quozl** [comment]
Well, I don't know.  Main reason it was not in this year's GSoC was that we had closed the window for proposals by the time this one arrived.  There's other barriers to the idea that may be raised; such as it being rote memorisation rather than constructivist approach to learning, that the activity may give wrong advice for the locality in which it is used, and that it could never be kept up to date.  I don't see any support for the idea from anyone else, and it hasn't been discussed on our project mailing list.

**Comment by quozl** [comment]
No support from others for this idea, so I'll close the issue until that support arrives.
